server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///lianxichaxun?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false